### ISSUE TITLE
Drawing test not pass

### ISSUE THREAD

**Issue by happydpc** [azhirnov/FrameGraph#16]
As the picture shows, there comes a mismatch.
![image](https://user-images.githubusercontent.com/771776/86606345-741c2a00-bfda-11ea-9dd7-aee30bfa1328.png)

**Comment by happydpc** [comment]
![image](https://user-images.githubusercontent.com/771776/86606462-9f067e00-bfda-11ea-9ed1-d17ccab31a3a.png)
![image](https://user-images.githubusercontent.com/771776/86606588-c9583b80-bfda-11ea-8044-81c783310b5f.png)

**Comment by azhirnov** [comment]
Some parameters depends on GPU. First set [UpdateAllReferenceDumps](https://github.com/azhirnov/FrameGraph/blob/dev/tests/framegraph/FGApp.cpp#L21) to `true`, run tests, then set back to `false`, tests should pass. With git check what changed in dumps: different staging buffer size is ok, unsupported mesh & rtx shader stages is ok.
Async compute test may fail because of task reordering - seed in hashmap changes at every start.
Shader debugger tests may fail because of mismatch in floating point numbers.

This tests are really helpful when you add new feature and can break anything. But they are not adapted to run on different GPUs.
